<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Setting;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $defaultSettings = [
            // School Information
            [
                'key' => 'school_name',
                'value' => 'Excellence School',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Name (Default)',
                'description' => 'The default school name (fallback)',
                'is_public' => true,
            ],
            [
                'key' => 'school_name_en',
                'value' => 'Excellence School',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Name (English)',
                'description' => 'The school name in English',
                'is_public' => true,
            ],
            [
                'key' => 'school_name_bn',
                'value' => 'এক্সেলেন্স স্কুল',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Name (Bengali)',
                'description' => 'The school name in Bengali',
                'is_public' => true,
            ],
            [
                'key' => 'school_address',
                'value' => '123 Education Street, City, State 12345',
                'type' => 'text',
                'group' => 'school_info',
                'label' => 'School Address',
                'description' => 'Complete address of the school',
                'is_public' => true,
            ],
            [
                'key' => 'school_phone',
                'value' => '+1-234-567-8900',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Phone',
                'description' => 'Main contact phone number',
                'is_public' => true,
            ],
            [
                'key' => 'school_email',
                'value' => 'info@excellenceschool.com',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Email',
                'description' => 'Main contact email address',
                'is_public' => true,
            ],
            [
                'key' => 'school_website',
                'value' => 'https://www.excellenceschool.com',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Website',
                'description' => 'Official school website URL',
                'is_public' => true,
            ],
            [
                'key' => 'school_principal',
                'value' => 'Dr. John Smith',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Principal',
                'description' => 'Name of the school principal',
                'is_public' => true,
            ],
            [
                'key' => 'school_established',
                'value' => '1995',
                'type' => 'number',
                'group' => 'school_info',
                'label' => 'Established Year',
                'description' => 'Year when the school was established',
                'is_public' => true,
            ],
            [
                'key' => 'school_motto',
                'value' => 'Excellence in Education',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Motto',
                'description' => 'School motto or tagline',
                'is_public' => true,
            ],
            [
                'key' => 'school_logo',
                'value' => '/images/logo.png',
                'type' => 'string',
                'group' => 'school_info',
                'label' => 'School Logo',
                'description' => 'Path to school logo image',
                'is_public' => true,
            ],

            // Academic Settings
            [
                'key' => 'academic_year',
                'value' => '2024-2025',
                'type' => 'string',
                'group' => 'academic',
                'label' => 'Current Academic Year',
                'description' => 'Current academic year',
                'is_public' => true,
            ],
            [
                'key' => 'semester',
                'value' => '1',
                'type' => 'number',
                'group' => 'academic',
                'label' => 'Current Semester',
                'description' => 'Current semester (1 or 2)',
                'is_public' => true,
            ],
            [
                'key' => 'max_attendance_percentage',
                'value' => '75',
                'type' => 'number',
                'group' => 'academic',
                'label' => 'Minimum Attendance Percentage',
                'description' => 'Minimum attendance percentage required for students',
                'is_public' => false,
            ],
            [
                'key' => 'passing_percentage',
                'value' => '40',
                'type' => 'number',
                'group' => 'academic',
                'label' => 'Passing Percentage',
                'description' => 'Minimum percentage required to pass exams',
                'is_public' => false,
            ],
            [
                'key' => 'max_students_per_class',
                'value' => '30',
                'type' => 'number',
                'group' => 'academic',
                'label' => 'Maximum Students per Class',
                'description' => 'Maximum number of students allowed per class',
                'is_public' => false,
            ],

            // System Settings
            [
                'key' => 'system_maintenance_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'system',
                'label' => 'Maintenance Mode',
                'description' => 'Enable maintenance mode for the system',
                'is_public' => false,
            ],
            [
                'key' => 'email_notifications',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'system',
                'label' => 'Email Notifications',
                'description' => 'Enable email notifications',
                'is_public' => false,
            ],
            [
                'key' => 'sms_notifications',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'system',
                'label' => 'SMS Notifications',
                'description' => 'Enable SMS notifications',
                'is_public' => false,
            ],
            [
                'key' => 'session_timeout',
                'value' => '30',
                'type' => 'number',
                'group' => 'system',
                'label' => 'Session Timeout (minutes)',
                'description' => 'User session timeout in minutes',
                'is_public' => false,
            ],
            [
                'key' => 'file_upload_max_size',
                'value' => '5',
                'type' => 'number',
                'group' => 'system',
                'label' => 'Maximum File Upload Size (MB)',
                'description' => 'Maximum file size allowed for uploads in megabytes',
                'is_public' => false,
            ],
            [
                'key' => 'allowed_file_types',
                'value' => 'jpg,jpeg,png,pdf,doc,docx',
                'type' => 'string',
                'group' => 'system',
                'label' => 'Allowed File Types',
                'description' => 'Comma-separated list of allowed file extensions',
                'is_public' => false,
            ],

            // Home About Section (Public)
            [
                'key' => 'home_about_title',
                'value' => 'About Our School',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Home About Title',
                'description' => 'Title for the About section on home page',
                'is_public' => true,
            ],
            [
                'key' => 'home_about_title_en',
                'value' => 'About Our School',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Home About Title (English)',
                'description' => 'Localized title (English) for the About section on home page',
                'is_public' => true,
            ],
            [
                'key' => 'home_about_title_bn',
                'value' => 'আমাদের বিদ্যালয় সম্পর্কে',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Home About Title (Bengali)',
                'description' => 'Localized title (Bengali) for the About section on home page',
                'is_public' => true,
            ],
            [
                'key' => 'home_about_description',
                'value' => 'We are committed to nurturing minds and building futures through excellence in education, diverse programs, and a caring community.',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Home About Description',
                'description' => 'Description text for the About section on home page',
                'is_public' => true,
            ],
            [
                'key' => 'home_about_description_en',
                'value' => 'We are committed to nurturing minds and building futures through excellence in education, diverse programs, and a caring community.',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Home About Description (English)',
                'description' => 'Localized description (English) for the home About section',
                'is_public' => true,
            ],
            [
                'key' => 'home_about_description_bn',
                'value' => 'আমরা শিক্ষা, নানাবিধ কর্মসূচি ও স্নেহশীল পরিবেশের মাধ্যমে মেধা বিকাশ ও ভবিষ্যৎ নির্মাণে প্রতিশ্রুতিবদ্ধ।',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Home About Description (Bengali)',
                'description' => 'Localized description (Bengali) for the home About section',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_name',
                'value' => 'Ms. Ayesha Rahman',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Head Teacher Name',
                'description' => 'Display name of the head teacher',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_name_en',
                'value' => 'Ms. Ayesha Rahman',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Head Teacher Name (English)',
                'description' => 'Localized head teacher name (English)',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_name_bn',
                'value' => 'মিসেস আয়েশা রহমান',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Head Teacher Name (Bengali)',
                'description' => 'Localized head teacher name (Bengali)',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_title',
                'value' => 'Head Teacher',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Head Teacher Title',
                'description' => 'Title/caption for the head teacher',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_title_en',
                'value' => 'Head Teacher',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Head Teacher Title (English)',
                'description' => 'Localized head teacher title (English)',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_title_bn',
                'value' => 'প্রধান শিক্ষিকা',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Head Teacher Title (Bengali)',
                'description' => 'Localized head teacher title (Bengali)',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_quote_1',
                'value' => 'Every child can learn, just not on the same day or in the same way.',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Head Teacher Quote 1',
                'description' => 'First quote for head teacher card',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_quote_1_bn',
                'value' => 'প্রত্যেক শিশু শিখতে পারে, শুধু একই দিনে বা একইভাবে নয়।',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Head Teacher Quote 1 (Bengali)',
                'description' => 'Localized head teacher quote 1 (Bengali)',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_quote_2',
                'value' => 'We foster curiosity, creativity, and character in every classroom.',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Head Teacher Quote 2',
                'description' => 'Second quote for head teacher card',
                'is_public' => true,
            ],
            [
                'key' => 'head_teacher_quote_2_bn',
                'value' => 'আমরা প্রতিটি শ্রেণিকক্ষে কৌতূহল, সৃজনশীলতা এবং চরিত্র লালন করি।',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Head Teacher Quote 2 (Bengali)',
                'description' => 'Localized head teacher quote 2 (Bengali)',
                'is_public' => true,
            ],
            [
                'key' => 'chairman_name',
                'value' => 'Mr. Karim Uddin',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Chairman Name',
                'description' => 'Display name of the school chairman',
                'is_public' => true,
            ],
            [
                'key' => 'chairman_name_bn',
                'value' => 'মি. করিম উদ্দিন',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Chairman Name (Bengali)',
                'description' => 'Localized chairman name (Bengali)',
                'is_public' => true,
            ],
            [
                'key' => 'chairman_title',
                'value' => 'School Chairman',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Chairman Title',
                'description' => 'Title/caption for the chairman',
                'is_public' => true,
            ],
            [
                'key' => 'chairman_title_bn',
                'value' => 'বিদ্যালয় সভাপতি',
                'type' => 'string',
                'group' => 'home_about',
                'label' => 'Chairman Title (Bengali)',
                'description' => 'Localized chairman title (Bengali)',
                'is_public' => true,
            ],
            [
                'key' => 'chairman_quote_1',
                'value' => 'Our mission is to create opportunities for every learner to thrive.',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Chairman Quote 1',
                'description' => 'First quote for chairman card',
                'is_public' => true,
            ],
            [
                'key' => 'chairman_quote_1_bn',
                'value' => 'আমাদের লক্ষ্য প্রতিটি শিক্ষার্থীর বিকাশের সুযোগ তৈরি করা।',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Chairman Quote 1 (Bengali)',
                'description' => 'Localized chairman quote 1 (Bengali)',
                'is_public' => true,
            ],
            [
                'key' => 'chairman_quote_2',
                'value' => 'Together with families, we build a stronger community through education.',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Chairman Quote 2',
                'description' => 'Second quote for chairman card',
                'is_public' => true,
            ],
            [
                'key' => 'chairman_quote_2_bn',
                'value' => 'পরিবারের সাথে একসাথে আমরা শিক্ষার মাধ্যমে শক্তিশালী সমাজ গড়ি।',
                'type' => 'text',
                'group' => 'home_about',
                'label' => 'Chairman Quote 2 (Bengali)',
                'description' => 'Localized chairman quote 2 (Bengali)',
                'is_public' => true,
            ],
        ];

        foreach ($defaultSettings as $settingData) {
            Setting::updateOrCreate(
                ['key' => $settingData['key']],
                $settingData
            );
        }
    }
}
